### PR TITLE
pass a copy of sceneDict to _makeSceneNxR. fixes #502.

### LINKED ISSUE #502: sceneDict error when running makeScene1axis
Passing a sceneDict into makeScene1axis that includes 'originx' or 'originy' doesn't get passed into the _makeSceneNxR subroutine.

> sceneDict = {'originx':0.05, 'originy':0.05, 'pitch':pitch,'hub_height':hub_height, 'nMods': nMods, 'nRows': nRows}
demo.makeScene1axis(module=mymodule,sceneDict=sceneDict)

demo.trackerdict['2021-11-06_1100']['scene'].sceneDict:
> {'tilt': 32.06,  'pitch': 6,  'clearance_height': 0.969,  'azimuth': 90.0, 'nMods': 20,  'nRows': 7,  'modulez': 0.02, 'axis_tilt': 0,

 **'originx': 0,  'originy': 0}**

### PR DESCRIPTION
**Pull request by cdeline**
instead of copying some of the keys of sceneDict into a sceneDict2 and passing that to _makeSceneNxR, this updates the appropriate keys, and makes sure that _makeSceneNxR is working from a copy.deepcopy of sceneDict.  Because it's a mutable type, this dict was being updated within the makeScene1axis loop. Using a copy here solves that problem.

### CODE REVIEW

**Comment by cdeline** [comment]
@shirubana  - I think this quick bug fix is ready to go.  Tests are passing aside for the minor delta in coveralls coverage.

**Comment by shirubana** [comment]
@cdeline  I see you removed removed **hub_height** from the dictionary. Is it still being saved somewhere? 

        # we no longer need sceneDict['hub_height'] - it'll be replaced by 'clearance_height' below
        sceneDict.pop('hub_height',None)

Other htan that I'm okay to merge

**Comment by cdeline** [comment]
So, inside makeScene1axis, we start with a `hub_height`, but that is changed to `clearance_height` for each timestamp when it is passed to `_makeSceneNxR`.  I could pretty easily add back the `hub_height` inside _makeSceneNxR if we want it on the sceneDict along with clearance_height - we would just report back both on Scene.SceneDict.

**Comment by shirubana** [comment]
Is hub _ height saved somewhere? It 's just for tracker systems to know what the hub height is, not the clearnace height

as a side note, we should round up to 2 decimals. The scene files are ridiculously long.

**Comment by cdeline** [comment]
Re: 'clearance_height' and 'hub_height': in `makeScene1axis`, when you pass in 'hub_height', it is converted to a 'clearance_height' and then passed in to `_makeSceneNxR`.  In order to keep warning messages from popping up (from `_heightCasesSwitcher` if you pass both clearance and hub height), I've removed hub_height from the sceneDict.  It sounds like we'd like to have both available in the trackerdict, so I will just add it back onto the sceneDict inside _makeSceneNxR.

**Comment by cdeline** [comment]
OK, I'll start looking at rounding in places.  Let's say to 3 decimals which would  be mm accuracy.

**Comment by cdeline** [comment]
OK, tests are passing, `hub_height` is back in the sceneDict saved to trackerDict.  Filename decimal points reduced.  Merging this.

**Pull request merged**
