### PR TITLE
Xand y

### PR DESCRIPTION
**Pull request by shirubana**

### CODE REVIEW

**Comment by cdeline** [comment]
@shirubana - I've updated the inputs to moduleAnalysis - -it's all based on just passing in a SceneObj, which has internal to it a .moduleDict and .sceneDict which contain all of the relevant parameters that you need.
There is one minor snag:  when I changed the unit tests to match the new parameter format, one of them (test_RadianceObj_1axis_gendaylit_end_to_end) now shows Wm2Front = 205 (previous v0.2.4 value) instead of 211 (your new updated value).   Maybe this is a difference of running on your machine versus mine??

**Comment by shirubana** [comment]
Possibly. Do you have the output csv file? Just to check the height/position of the sensors.... since we have that inner confusing of height and hub_height just want to make sure the correct thing is being assigned.

**Comment by cdeline** [comment]
OK, I figured it out.   If you look at the commit history, the unit tests was broken when you did the commit for positive tilt and azimuth fix.  I think what happened for a while was we were incorrectly calculating the row number with rowWanted.  When I manually change the unit test from rowWanted = 3 to rowWanted = 1, then we match the higher Wm2Front = 211 and Wm2Back = 39.  So when you changed back to the positive tilt and azimuth fix, we went back to querying the correct row.

**Comment by cdeline** [comment]
Version 0.2.4 test result:


x | y | z | rearZ | mattype | rearMat | Wm2Front | Wm2Back | Back/FrontRatio
-- | -- | -- | -- | -- | -- | -- | -- | --
-0.9732743 | 1.988 | 4.366989 | 1.514337 | a7.2.a0.PVmodule.6457 | a7.2.a0.PVmodule.2310 | 202.9694 | 38.3681933 | 0.18903344
-1.946549 | 1.988 | 4.366989 | 2.425663 | a7.2.a1.PVmodule.6457 | a7.2.a1.PVmodule.2310 | 206.870167 | 45.92472 | 0.22199672


Version XandY test result (now):

x | y | z | rearZ | mattype | rearMat | Wm2Front | Wm2Back | Back/FrontRatio
-- | -- | -- | -- | -- | -- | -- | -- | --
-10.94236 | 1.988 | 1.604337 | 1.514337 | a6.2.a0.PVmodule.6457 | a6.2.a0.PVmodule.2310 | 202.824967 | 39.2747133 | 0.1936375
-11.91564 | 1.988 | 2.515663 | 2.425663 | a6.2.a1.PVmodule.6457 | a6.2.a1.PVmodule.2310 | 207.0356 | 46.1065233 | 0.22269745

**Comment by shirubana** [comment]
Ok... xcellent!

**Comment by cdeline** [comment]
Hey - I checked our output against SAM and previous runs.  there are minor differences around sunrise and sunset.  For example - the Richmond TMY file has a timepoint at 2/26 18:00 with GHI = 56, although the sunset time is calculated at 17:59.  Our bifacial_radiance code ignores this point with a solar elevation of -0.9 degrees, while the SAM output calculates solar elevation at 5.5 degrees, with POA front irradiance = 95 Wm-2.  So apparently SAM is using a different solar position algorithm than we are.  I don't think this is a big issue - just mainly something to document.

**Comment by shirubana** [comment]
MAkes sense. That's what I noticed when I did the  comparison with SPA:

image


But since we arer using PVlib for both calculating the sun position adn the tracker position we should be fine :D unless this bugs us out too much.

**Comment by cdeline** [comment]
OK, please merge this into development.  I still may do some cleanup activity, which could change some of the filenames and input / output parameters from some functions.  Hopefully that won't cause too much disruption.

**Comment by shirubana** [comment]
Sweet! 

I'll close the branch.. then.. I think...

**Pull request merged**
