### PR TITLE
Issue68 hourly albedo

### PR DESCRIPTION
**Pull request by cdeline**
Allow RGB and time-series albedo in bifacial_radiance.

### CODE REVIEW

**Comment by cdeline** [comment]
@shirubana - take a look.  Things are mostly the way you left them.  I did reconfigure some of the albedo checking and added a `printGroundplane()` function in GroundObj to return the correct string for generating the ground text in the sky.rad file.  That way we can keep some of the albedo handling details out of gendaylit and gencumsky.  It also streamlines these functions.

I did include your API change for gendaylit to make metdata an optional parameter, and changed the example notebooks and pytests accordingly.

**Comment by cdeline** [comment]
ps there are a pile of Auto-PEP8 changes in spacing etc mixed in there too.

**Comment by shirubana** [comment]
i'll check it out.!! ty!!

**Comment by cdeline** [comment]
pps - I reverted all the autoPEP8 changes to make it easier to review changes.  they're stashed in the PEP8_cleanup branch and can be applied later.

**Pull request merged**
