### PR TITLE
Multi scene objs

### PR DESCRIPTION
**Pull request by cdeline**
Allow multiple scene objects to be tracked at the same time by the RadianceObj.  This is accomplished by running makeScene multiple times, each one appends a new SceneObj to RadianceObj.scenes which is a new list to track scene objects.

todo:

- [ ] ~CompileResult is hardcoded to run once over all sceneNums, even if bifacial modules and details are different.~ (will be handled in new PR tied to #512 )
- [x] multiple makeScene and makeScene1axis typically over-wrote the scene instead of append.  Include append option instead of the over-write default.
- [ ] ~Functionality to pop scenes from trackerdict if desired. This may mess up some naming, for instance if we have Scene0, Scene1, Scene2 and Scene1 gets popped.  May require renaming the remaining scenes...~
- [x] RadObj.addPiles needs to be moved out of RadObj and refactored to work in makeScene1axis (adding issue #505 to track this separately)
- [x] Check appendtoscene function- it's currently both in RadObj and SceneObj, and operates differently in each place...
- [ ] ~In modelchain, sceneNum is hardwired to 0 in  simulationParamsDict.get('saveImage') (line 253 of modelchain)~ (OK as-is...)
- [x] notebooks need to be updated to demo new functionality
- [ ] ~Warning for tracker gencumsky if you have multiple scenes - the trackers need to have the same angles at the same times.  Otherwise skyfiles will need to be created specific to the scene...~
- [x]  Manual text and custom objects for sceneObjs
- [x]  readthedocs API and whatsnew
- [x] Code changes are covered by tests
- [ ] Code changes have been evaluated for compatibility/integration with GUI
- [ ] ~New functions added to `__init__.py`~

### CODE REVIEW

**Comment by cdeline** [comment]
Moved over to PR #488

**Comment by cdeline** [comment]
OK, nevermind, we'll work on this branch to make it easier.  Closing #488

**Comment by shirubana** [comment]
calculateResults() failing with multi scene and multi result objects...

**Comment by shirubana** [comment]
backseat driving --- there is an option of AgriPV = True which basically bypasses calculating module results (I think it might also look at only 1 single csv result front or back, I don't recall), but it was also not working with multi result/object

**Comment by cdeline** [comment]
Tests are passing, just a coveralls error.  This is ready to merge with development.  We can update journals from there.

**Pull request merged**
