### PR TITLE
Adding updated Linux gencumulativesky binary with support for -E option.

### PR DESCRIPTION
**Pull request by jalderman9**
Adding updated Linux gencumulativesky binary with support for -E option. This was compiled from sources available at http://daysim.ning.com/page/download. Fixes NREL#129 fixes NREL#119

### CODE REVIEW

**Comment by cdeline** [comment]
Hi Jason, thanks for finding this file.  We are hoping to avoid any license issues with gencumulativesky - could you please give me some information about where this particular gencumulativesky binary originated, and what license it's shared under including proper attribution requirements?  Thanks!

**Comment by jalderman9** [comment]
@cdeline Unfortunately none of the sources have any license information that I can find.  I compiled the linux binary from sources as described in #129 

The original source only has this:
```// GenCumulativeSky was conceived, developed and validated by Darren Robinson and Andrew Stone for efficient solar irradiation modelling using RADIANCE
// When using GenCumulativeSky they would be pleased if you would ackowledge their work by referring to the following article: "Robinson, D., Stone, A., 
// Irradiation modeling made simple  the cumulative sky approach and its applications, Proc. PLEA 2004, Eindhoven 2004."
```
Hopefully Christoph responds to @mikofski 

It might also be worth reaching out to Darren Robinson: https://www.sheffield.ac.uk/architecture/people/academic/darren-robinson

**Comment by cdeline** [comment]
I think (correct me if I'm wrong) that all I merged into development was the new Linux executable.  Any of the other changes were because it was based on Master instead of Development where the #134 changes were already pulled.

**Comment by cdeline** [comment]
@mikofski  - check the current development branch to make sure your changes are still in there - it looks like everything's ok.

**Pull request merged**
