### PR TITLE
Load functionality for v0.2.4 release

### PR DESCRIPTION
**Pull request by cdeline**
@shirubana :  I'm making a pull request to finalize this load functionality.  The first thing I did was to rebase your commits based on v0.2.4, so everything should  look the same as load_functionality_silvana except it's a bit neater.  

Here are a couple things that I would like to do:
1. can we either remove the groupbycell example files into a private fork of yours, or move them to the docs folder?
2. I think that some of these load and analysis functions might work best in a separate .py file in the \bifacial_radiance\ directory.  We can keep analysis a bit separate from the core simulation functions.  If you're ok with that, I can get started on the new file and linking back to our routine.
3. We should include some tests and examples for the save, load and cleaning functions.  That way we can confirm that any changes we make don't break the basic functionality.

Let me know if you want to take a stab at any of these things, or if you'd prefer that I start on them first.  Thanks!

### CODE REVIEW

**Comment by shirubana** [comment]
1. Ah! I was wondering where I had left that file....thanks for finding it 💃 ... I'll copy it and take care of it. I need to continue working on it.
2. I had thought about this, because it's similar to what we did with bifacial_vf and I think it's a great idea.
3. Agreed. I think it should be implemented into the main workflow though, because again if someone runs 2-UP with gap they will get a wrong result spit out at the end. I had a journal with an example but it must be outdated by now.

I can tackle this ! 

(I can send some other code your way if you're idle on rotating around the torque tube hahahahaha like that ever happens).

**Comment by shirubana** [comment]
Load and clean functions are in a separate .py file now. Not sure what else I need to do for the review? However all checks have failed since late last week on this branch. I have clicked on them but I can't figure out what's going on or how to go about it.

**Comment by cdeline** [comment]
@shirubana - go ahead and merge your load functionality unit tests for read1Result and deepcleanResult into this branch and I'll take a look at them.

**Comment by shirubana** [comment]
Various things Im' struggling with with the branch off of this version ~

1. the import of load.py is not working for me. I had to hard code it to 
from load import loadRadianceObj, read1Result, loadtrackerdict, _loadTrackerDict, deepcleanResult

2. Running the TorqueTube Journal example, I am getting wrong values in the sensor positions. I am very confused because yesterday it was working well. I'll go back in a bit to my branch of the Module Agnostic Orientationand check that journal again. 😠 

3. This pytest branch that I'm trying to merge doesn't have the new py-test modifications needed for the Module Agnostic Orientation branch. This isj ust for the read and clean functionality.

4. Also this version's pytest (and my pytest branch) both are crying wolf when running for me...... One issue is that test\materials\ground is not bing created or something. I haven't figured that out yet.

**Comment by shirubana** [comment]
Solved 1-3,
for 4, my pytest worked for a while until I merged the new load_functionality changes from today.  The issue I'm finding is that 

1.  'materials\\ground.rad'  does not get created...
2. And since the way that you "load" load.py in bifacial_radiance is not working for me, then test_load.py fails.

 I'll try to investigate how to solve it.

**Comment by cdeline** [comment]
I'm merging this load functionality - checks are passing and we have new unit tests for the new features. Thanks @shirubana !

**Comment by shirubana** [comment]
@cdeline we can close this branch, load_functionality silvana branch and v_0_2_4 branch now?

**Comment by cdeline** [comment]
Yes, these can be removed.


On Feb 28, 2019, at 4:47 PM, Silvana Ayala <notifications@github.com<mailto:notifications@github.com>> wrote:


@cdeline<https://github.com/cdeline> we can close this branch, load_functionality silvana branch and v_0_2_4 branch now?

**Pull request merged**
