### PR TITLE
Orientation agnostic branch

### PR DESCRIPTION
**Pull request by shirubana**
This is ready! Added some changes to pytest and now it all matches beautifully :)

### CODE REVIEW

**Comment by shirubana** [comment]
DON'T LET THE RED X FOOL YOU, PYTEST IS WRONG NOT MY CODE MUAHAHAHAA 

(see the new pytest 🗡 )

**Comment by shirubana** [comment]
@cdeline pytests branch for test_load.py merged into this one. this one also has pytest changes but for bifacial_radiance itself. .... It's still not flowing smoothly but neither is load functionality_cdeline for me at all.

**Comment by cdeline** [comment]
@shirubana I'll be able to get the load routines updated and merged first.  I still have some reservations about what we're doing with the orientation agnostic stuff, and we may want to reconsider a couple of things.  For instance, being able to rotate modules into landscape configuration may still be a nice thing to have - the question is how to facilitate this without totally messing up tracking.

**Comment by cdeline** [comment]
Tests are passing for the load functionality.  I'm merging these into load_functionality_cdeline then merging that branch into v0.2.4

**Comment by cdeline** [comment]
We still need to figure out all of the module orientation stuff..

**Comment by shirubana** [comment]
I'm almost done with the new landscape version (couldn't save the previuos one) and journal sanity checks for all cases ~ will write a pytest afterwards.

The agnostic should be working good (if you change the pytest scene.text to what I had). 

Another option I thought of last night ~~ what if we include a "flip" horizontal adn flip vertical option for when people use CAD? I've seen this in programs that import CAD, which for some reason even if you are doing it "the right way in CAD" when you import sometimes things are flipped weird.  Could be a separate function. If they are using CAD they should be expected to check their geometry in Radiance visually anyways :).

**Comment by cdeline** [comment]
Looks like the tests aren't passing - possibly because of a change to how load.py is imported.  Could you revert back to the way it is in the current branch of v0.2.4?  the proper way is `from . import load` not `from load import *`

**Comment by cdeline** [comment]
@shirubana :  I pushed a few commit changes that you should review.  In particular, I replaced `psx`, `panelgap` and `tubeZgap` with `xgap`, `ygap`, and `zgap`  respectively.  The original inputs will still work, just results in a text warning.  Also, if you try to pass in a 'landscape' orientation, makeScene will return with an error.  this may prevent people from getting results that they don't want when re-running old files that still included orientation = 'landscape'.

**Comment by shirubana** [comment]
It looks good! Sorry I forgot those where the names we wanted u_u

**Comment by shirubana** [comment]
You are being so nice with people, doing the search for psx on makeScene. I don't think that feature was in v_0_2_3 long enough for people to catch on... I actually don't think that got published at all. Maybe we can just delete that variable and warning I'm gonna edit just that

**Comment by cdeline** [comment]
@shirubana However, the tests are still failing on `test_RadianceObj_high_azimuth_angle_end_to_end()` possibly because of  some un-tested change.  When I run the test on v0.2.4, the scene.frontscan goes from y = -0.108 to -0.9.  In orientation agnostic branch, the scan is from y = 0.09 to 0.84.  So something is going on with that.  I'm attaching the two result files in case you have time to dig into this.
[results_highAzimuth_orientationAgnostic.txt](https://github.com/NREL/bifacial_radiance/files/2891817/results_highAzimuth_orientationAgnostic.txt)
[results_highAzimuth_V0.2.4.txt](https://github.com/NREL/bifacial_radiance/files/2891818/results_highAzimuth_V0.2.4.txt)

**Comment by shirubana** [comment]
ok, I think I know what's going on. I'll fix it!

**Comment by cdeline** [comment]
@shirubana  I think that we're close here with the landscape orientation stuff, but I think that we got a second unrelated issue here with the scans not applying consistently with 1-axis tracking.  It seems like we have a lot of fixes and band-aids to address the fundamental issue that we are changing the azimuth by 180 degrees rather than just moving the tracker to a negative tilt angle.  Here's what I propose we do:
1. you submit an issue to the issue tracker regarding the scans not applying consistently for 1-axis tracking.
2. I'll create a new branch 'negative tilt angles' that will help to identify if we can clean a lot of the scan issues up just by moving the tracker to negative tilt.  The scans may actually work themselves out without needing all of the cleanup stuff.
3. I'll approve the pull request for the landscape updates.

OK?

**Comment by shirubana** [comment]
So I am confused, becuase I don't think it's the negative tracking the issue ~ it's when it is not at 90 or 270 or 180 degrees azimuth. The one test that is failing is at 30 degrees azimuth so one of the other sensors locations that I didn't really check too much is conflicting...

**Comment by shirubana** [comment]
Which by the way even the 30 degree azimuth results from before were wrong, because the points should have moved in X and Y and we were still getting  X = 0.

**Comment by shirubana** [comment]
@cdeline I FIGURED IT OUT

It was the fault of  orientation variable, which we deprecated then reintroduced in the middle of makeSceneNxR( definition, and since we are passing makeScene without variables it was assigning the azimuth to the orientation. .......................... so dumb.

It matches perfectly now 💃

**Comment by shirubana** [comment]
It works it works it works it works  it works

it works

**Comment by cdeline** [comment]
Some last remaining things before the merge:
Some files were added to this branch that may not be required: 
2019-02-19_174046.oct and other .oct files in the /tests/ folder
a couple files in the /skies/ folder
a couple files in the /results/ folder.
I've removed these.  Also, is the Module Agnostic Orientation Sanity Check.ipynb intended to get merged into v0.2.4, or just stay in this branch?

**Comment by cdeline** [comment]
@shirubana let me know if you agree that this can get merged.  There are a couple of files in v0.2.4 that are scheduled to be deleted - Group by Cells example.ipynb and MultipleScenesTest.ipynb.  Are these ok to be removed?

**Pull request merged**
