### PR TITLE
download, patch, and build gencumulativesky source

### PR DESCRIPTION
**Pull request by mikofski**
This is a multiplatform build helper that is part of setup.py, and uses distutils to download, patch, and build gencumsky from the source on any platform: windows, mac, and linux.

### CODE REVIEW

**Comment by mikofski** [comment]
Hi @cdeline, @jalderman9, @tcapelle, @shirubana,

Although this is still a WIP, it is working - you can try it with either:

    $ python setup.py bdist_wheel  # build a wheel with gencumulativesky.exe

or

    $ python path/to/gencumsky/__init__.py build  # just download, patch, and build

to clean use

    $ python path/to/gencumsky/__init__.py build  # just download, patch, and build

#### details:
- alternative to #153 that also resolves #129 
- downloads the source from the link in the instructions, so no license is required
- patches the source as needed
    - currently only patches the capitalization issue for `climateFile.h`
- builds the source on the CI server when it is bundled into a wheel
- multiplatform: works on
    - mac os x
    - windows
    - linux
- allows users on linux and mac os x to build and install on their own using what ever toolchain they choose, EG: not just limited to GCC-3.7 or clang, etc.

IMO this is a sustainable solution that makes sure that the current binary is always built using the correct toolchain, and avoids any binary incompatibiltiies. It also uses transparent Python commands from distutils to build on any platform that Python natively supports.

#### Still to do:
- [ ] diff the current version of DaySim and apply the patches necessary to make the older zipped source provide the -E option, not sure if this is doable or not
- [ ] maybe make the location of the source and build output more flexible, and move the script to a script file parallel to `setup.py`
- [ ] some testing of the binary and the build script?
- [ ] discuss options with others regarding using `distutils` versus just more explicit `subprocess.Popen`?

**Comment by mikofski** [comment]
There is a possible question about how to deploy this
- if `gencumsky` is built by the CI, then that sorta makes the wheel platform specific, even though `gencumsky` is the only binary in there
- `linux` can't deploy platform specific wheels, without using `manylinux`, `manylinux2`, etc.
- currently the package is deployed as pure-python by the CI to pypi, which is convenient

It seems more advantageous to keep the package pure-python, and perhaps force the user to build `gencumsky` on first use? The windows binary doesn't have to be built, already part of package.

**Comment by mikofski** [comment]
Another perhaps easier idea would be to split gencumsky off into a new repo, make it platform specific, and make it a requirement of bifacial_radiance - then bifirad could stay neutral, and folks on every platform can run it. Anyway, we can just shelve this until people start complaining. If there's no problem now, we can just close this.

**Comment by jalderman9** [comment]
@mikofski Attached is a patch that will update the old gencumulativesky sources from the zip file to the daysim version.

I agree that a separate repo is probably a good idea.  
[gencumulativesky_update.patch.gz](https://github.com/NREL/bifacial_radiance/files/3736771/gencumulativesky_update.patch.gz)

**Comment by mikofski** [comment]
Thanks for the patch. Applying it using using [python-patch](https://pypi.org/project/patch/) is not so elegant, so I'm thinking that actually it would be better to apply the patch once and commit source to repo. This has the advantage of freezing it where we want it

Is there any reason it's not okay to redistribute this patched source code? IMO it should be okay, and it makes this script much simpler!

**Comment by jalderman9** [comment]
@mikofski I agree that it's ok to make the patched sources available.  The license explicitly states this.

**Comment by mikofski** [comment]
Hi @cdeline , @shirubana , @jalderman9 , @tcapelle,

Okay, this is working, and builds wheels for linux, windows, and mac osx,

    $ python setup.py bdist_wheel

but I'm not really sure what (if anything) you want to do with it now. Some questions, options:

1. do nothing, mac and linux users can grab the patch, apply it them selves, and run `make`, the windows binary is already available, although it was compile with debug flags so it's about 3x larger than it needs to be, the new binary is only 35-KB, while the old on is 1.1-MB
2. use it, get an azure pipeline going, and create windows wheels - what CI allows free mac wheels? Circle? AppVeyor? Travis.com?
3. move it to a new repository and deploy it as a separate package, require it in bifirad, but who will do this? NREL?
4. copy the source to the repo, since the license allows this, and we are including the license, rather than downloading and patching every build. This would freeze the build the way we 
5. tweeks, changes, tests, etc. coveralls is upset that this adds code with not tests - another argument for moving gencumsky to its own repo/package.

Also what's the deal with `falsecolor.exe` is it used anywhere? It's a window binary, so it won't work for linux or mac. It's 3MB, is it necessary.

**Comment by mikofski** [comment]
closed in favor of #182 - I will keep this in [my personal bifirad repo](../../../mikofski/bifacial_radiance/tree/build_src/gencumsky)

**Pull request closed without merging**
