### PR TITLE
sphinx

### PR DESCRIPTION
**Pull request by shirubana**

### CODE REVIEW

**Comment by cdeline** [comment]
I think we need to have @kanderso-nrel help us move the tutorial files back into /docs/  instead of putting them in /sphinx/source/  if at all possible.  Having the tutorial files more easily findable for users would be a big help.

**Comment by kanderso-nrel** [comment]
@cdeline yes the new location is definitely difficult to discover when browsing the repository.  #437 has some discussion on possible workarounds and implements the one I think is best in this case.  If that approach is accepted, I suggest merging #437 to `main` first so that this PR is automatically updated (and simplified by virtue of eliminating the notebook diffs).

**Comment by cdeline** [comment]
Looks good on my computer, I had to filter out the .ipynb_checkpoints directory though - it was complaining if it tried to copy that.  I'll merge this to main and development.

**Comment by cdeline** [comment]
Dev is still broken but not because of this...

**Pull request merged**
