### PR TITLE
Hourly fixed workflow

### PR DESCRIPTION
**Pull request by cdeline**
This fixes a bunch of things with the hourly fixed tilt workflow.  It leverages the trackerdict structure by setting tilt and azimuth to fixed.  It adds a new optional fixed_tilt_angle to main.set1axis() which triggers a fixed tilt simulation to be returned in a trackerdict.  it still uses the axis_azimuth input as the fixed tilt azimuth angle though...  hopefully this isn't too confusing.  
I've checked the pytests, and a few GUI options.  Please check that all GUI functions are still working.

### CODE REVIEW

**Comment by cdeline** [comment]
Oops - the gui input tracking_hourly for the full year isn't working correctly.

**Comment by cdeline** [comment]
I think all of the gui buttons should be working now...

**Comment by cdeline** [comment]
OK, I merged main into development so it should be up to date.  If you want the EUPVSEC stuff too, you can merge from development into your EUPVSEC branch once we get this pull request finished.

**Comment by cdeline** [comment]
@shirubana :  Here's a question about default behavior  when both daydateSimulation and timestampRangeSimulation are False.  In this case, the modelChain always assumes that you want a full annual simulation - whether it's a cumulativesky or hourly simulation, and regardless of whether you pass start / end time details in the timeControlParamsDict, which are ignored unless you specificially trigger a limited time simulation with either of the above flags (daydate or timestamprange).  OK?

**Comment by shirubana** [comment]
I think that sounds good.

**Comment by shirubana** [comment]
Maybe it would need some sort of warning: "Information for day start/end, included, but since no specific time-simulation selected, proceeding to calculate WHOLE year"

**Comment by shirubana** [comment]
this is a helper function for (me) the jupyter journals -- in case you're wanting to do a fixed tilt simulation and need to know the tracker's angles.

Right now fixed tilt is the only way to do multiple scene objects so I think we should leave this for when someone wants to do a tracker field with fixed tilt in it too..

**Comment by cdeline** [comment]
This looks good, I'm going to merge it into development.

**Comment by shirubana** [comment]
🥇

**Comment by cdeline** [comment]
@shirubana  - I'm tagging this as a development release:  0.3.2-dev1

**Comment by shirubana** [comment]
sweet.

I'm going to delete the Master EUPVSEc branch then ~~

**Pull request merged**
